
SOCIAL_AUTH_TWITTER_KEY = '4Hb0g0XpYGmk4bCk4a5BXieKV'
SOCIAL_AUTH_TWITTER_SECRET = 'oaPvYtgc4Kkng4wA7Qy3UfgfE5uo8CpxKTMdutXYDrroJ7cuwi'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/myaccount'
SOCIAL_AUTH_LOGIN_URL = '/login'
